### ISSUE TITLE
Preliminary Workspace/KWin task list

### ISSUE THREAD

**Issue by subdiff** [blue-systems/plasma-wayland#1]
* Screen capture / Remote desktop:
  * General task: https://phabricator.kde.org/T5653
  * Additional PipeWire task: https://phabricator.kde.org/T7785
* Mouse KCM:
  * Wayland specific mouse KCM using Libinput in the style of the touchpad KCM
* Gamma correction:
  * Task: https://phabricator.kde.org/T4465
* Don't force QT_QPA_PLATFORM=wayland:
  * instead allow every Qt based application to decide for itself, if it wants to run as Wayland native or still via Xwayland (otherwise problems with some apps, for example Telegram),
  * provide simple functionality in frameworks for our apps to choose this.
* Create fallback mechanism to X for Nvidia users

**Comment by star-buck** [comment]
Dead keys seem a problem: https://lwn.net/Articles/746759/

**Comment by subdiff** [comment]
> Dead keys seem a problem: https://lwn.net/Articles/746759/

Martin commented, that this problem will be fixed in Qt 5.11.

>* Screen capture / Remote desktop:
>* Mouse KCM:
>* Gamma correction:
>* Don't force QT_QPA_PLATFORM=wayland:
>* ~~Create fallback mechanism to X for Nvidia users~~ -> not needed since Wayland won't be default in 5.13

These tasks have been officially formulated in the meantime. They are available on Phab now as a milestone of the Plasma project:
https://phabricator.kde.org/project/view/265/ 

Closing therefore this preliminary task list.
